filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/inputlogs/*
    - /usr/share/filebeat/inputlogs/**/*
  fields:
    log_type: ${LOG_TYPE:application}
    application: ${APPLICATION_NAME:myapp}
  fields_under_root: ${FIELDS_UNDER_ROOT:false}
  scan_frequency: ${SCAN_FREQUENCY:10s}
  harvester_buffer_size: ${FILEBEAT_BUFFER_SIZE:16384}
  max_bytes: ${FILEBEAT_MAX_BYTES:10485760}
  json.keys_under_root: ${JSON_KEYS_UNDER_ROOT:true}
  json.add_error_key: true

# Output directly to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "gis-logs-%{+yyyy.MM.dd}"

# Setup template
setup.template.name: "gis-logs"
setup.template.pattern: "gis-logs-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat.log
  keepfiles: 5
  rotateeverybytes: 10485760

# Processors
processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~
- add_kubernetes_metadata: ~
- add_fields:
    target: ''
    fields:
      log_source: filebeat
      environment: ${ENVIRONMENT:development}

# Monitoring
monitoring.enabled: false

# Performance settings
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s