logging:
  level: "info"
  file: "/tmp/pxpoint-logs/gis-app.log"
  max_file_size: 5242880  # 5MB
  max_files: 10
  pattern: '{"timestamp":"%Y-%m-%dT%H:%M:%S.%fZ","level":"%l","logger":"%n","message":"%v"}'
  
  # Component-specific loggers
  loggers:
    GeocodingAPI:
      level: "debug"
    HttpServer:
      level: "info"
    ShapefileReader:
      level: "debug"
    Geocoder:
      level: "info"
    SpatialIndex:
      level: "warn"
    PolylineGeometry:
      level: "debug"
    BoundingBox:
      level: "debug"
      
