cluster.name: "gis-logging-cluster"
node.name: "elasticsearch"

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings for single node
discovery.type: single-node

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory settings
bootstrap.memory_lock: true

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Index settings
action.auto_create_index: "+gis-*,+filebeat-*,+logstash-*,-*"

# Performance settings
indices.memory.index_buffer_size: 10%
indices.memory.min_index_buffer_size: 48mb

# Logging level
logger.level: INFO