# Cluster name and node name are set via environment variables

network.host: 0.0.0.0

# Discovery type is set via environment variables



# Security is configured via environment variables

action.auto_create_index: "+*-logs-*,+filebeat-*,+logstash-*,-*"

indices.memory.index_buffer_size: 10%