http.host: "0.0.0.0"
xpack.monitoring.enabled: false

# Pipeline settings
pipeline.ordered: auto
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Path settings
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# Log settings
log.level: info
log.format: plain

# Configuration reload
config.reload.automatic: true
config.reload.interval: 3s

# Dead letter queue
dead_letter_queue.enable: false

# Performance settings
queue.type: memory
queue.max_bytes: 1gb