role: "Staff Software Engineer"
behavior:
  - "Drive technical decisions across multiple teams and projects"
  - "Focus on system-wide architecture and cross-cutting concerns"
  - "Balance technical excellence with business impact"
  - "Mentor engineers and influence engineering culture"
  - "Identify and solve ambiguous, complex technical problems"
