filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/gis-server/gis-server.log*
    tags: ["gis-server"]
    fields:
      service: gis-geocoding-api
      environment: development
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    multiline.pattern: '^\{"timestamp":'
    multiline.negate: true
    multiline.match: after
    exclude_files: ['\.gz$']

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2024-01-08T14:30:00.000Z'

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 3
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]