filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/inputlogs/**/*
  fields:
    log_type: ${LOG_TYPE:application}
    application: ${APPLICATION_NAME:myapp}
  fields_under_root: ${FIELDS_UNDER_ROOT:false}
  scan_frequency: ${SCAN_FREQUENCY:10s}
  harvester_buffer_size: ${FILEBEAT_BUFFER_SIZE:16384}
  max_bytes: ${FILEBEAT_MAX_BYTES:10485760}
  json.keys_under_root: ${JSON_KEYS_UNDER_ROOT:true}
  json.add_error_key: true

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

setup.template.enabled: false
setup.ilm.enabled: false

logging.level: info

# Processors
processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_fields:
    target: ''
    fields:
      log_source: filebeat
      environment: ${ENVIRONMENT:development}
